### ISSUE TITLE
Implement task lists from GFM

### ISSUE THREAD

**Issue by RoadTrain** [ap0llo/markdown-generator#92]
Hello!
I think it would be cool to have task lists extension implemented:
https://github.github.com/gfm/#task-list-items-extension-

For now I had to use raw span in order to have this rendered properly.

**Comment by ap0llo** [comment]
Yes, task lists would be a nice addition. 

Shouldn't be too hard to add, I'll give it a try when I find time

**Comment by RoadTrain** [comment]
@ap0llo Hello! Any progress so far?
I think I might have time to help implement it :)

**Comment by ap0llo** [comment]
@RoadTrain Thanks for offering help and sorry for the delayed response.

I actually looked into this today and added support for task list items in #113.
The implementation turned out to be pretty straightforward but it introduces a breaking change in the library. 

I'm currently undecided if I should accept the breaking change or if I can find way to avoid it.

**Comment by RoadTrain** [comment]
@ap0llo Thanks!
I generally think breaking changes are OK as long as:
1. Major version is bumped
2. Some notification is published in release notes.

Finding a way to avoid breaking changes is good, but if it's too hacky, it's better to go with breaking changes instead. Especially to simplify further maintenance of the library.

Just my 2 cents :)

**Comment by ap0llo** [comment]
So, I decided to keep the breaking change and bump the major version to 3.

You can get a pre-release build with task list support from the [MyGet feed](https://www.myget.org/feed/ap0llo-markdown-generator/package/nuget/Grynwald.MarkdownGenerator)

**Comment by RoadTrain** [comment]
Thanks a lot! Will test it next week.
